In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
Outlook =["Sunny","Sunny","Overcast","Rain","Rain","Rain","Overcast","Sunny",
                "Sunny","Rain","Sunny","Overcast","Overcast","Rain"]
Temperature = ["Hot","Hot","Hot","Mild","Cool","Cool","Cool","Mild",
                    "Cool","Mild","Mild","Mild","Hot","Mild"]
Humidity = ["High","High","High","High","Normal","Normal","Normal","High",
                 "Normal","Normal","Normal","High","Normal","High"]
Wind = ["Weak","Strong","Weak","Weak","Weak","Strong","Strong","Weak",
             "Weak","Weak","Strong","Strong","Weak","Strong"]
Decision = ["No","No","Yes","Yes","Yes","No","Yes","No",
                 "Yes","Yes","Yes","Yes","Yes","No"]


In [3]:
#All the above are string data(object), machine cannot understand. We need to convert it to Numeric
#So here we're performing Encoding.

#Encoding
 #1. Label Encoding
 #2 OneHoot Encoding
 #3.Get_Dummies


In [4]:
#Label Encoding
#Label Encoding is a data preprocessing technique used in Machine Learning to convert categorical 
# values (like words or labels) into numerical values (integers), because most ML algorithms 
# work with numbers only.

#If there 10 different obejctes, the numerical values are 0,1,2,3,4......,10


In [5]:
from sklearn.preprocessing import LabelEncoder
lab=LabelEncoder()
Outlook_encoder = lab.fit_transform(Outlook)
Outlook_encoder

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [6]:
temp_encoder=lab.fit_transform(Temperature)
temp_encoder

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [7]:
humidity_encoder=lab.fit_transform(Humidity)
humidity_encoder

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0])

In [8]:
Wind_encoder=lab.fit_transform(Wind)
Wind_encoder

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [9]:
#To combine all imputs into one using Zip

feature=list(zip(Outlook_encoder,temp_encoder,humidity_encoder,Wind_encoder))
feature #All the input variables are now in feature variable

[(np.int64(2), np.int64(1), np.int64(0), np.int64(1)),
 (np.int64(2), np.int64(1), np.int64(0), np.int64(0)),
 (np.int64(0), np.int64(1), np.int64(0), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(0), np.int64(1)),
 (np.int64(1), np.int64(0), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(0), np.int64(1), np.int64(0)),
 (np.int64(0), np.int64(0), np.int64(1), np.int64(0)),
 (np.int64(2), np.int64(2), np.int64(0), np.int64(1)),
 (np.int64(2), np.int64(0), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(1), np.int64(1)),
 (np.int64(2), np.int64(2), np.int64(1), np.int64(0)),
 (np.int64(0), np.int64(2), np.int64(0), np.int64(0)),
 (np.int64(0), np.int64(1), np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(2), np.int64(0), np.int64(0))]

In [10]:
#Model Creation

# 3 type of classifiers

#1.Gaussian()
#2.Multinomial
#3.Bernouli


#Where Gausian classifier?
   #If the given data is a contunious data(Numerical) set, then we use Gausian Classifier

#Multinomial classifier
  #If the given data is a descrete data/object data(string) set, then we use Multinomial Classifier

#Bernouli Classiifer
   #If the data is negative, we use Bernouli classifier



In [24]:
#Model creation

from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB() #object created
model.fit(feature,Decision)
print(model.predict([[2,0,0,0]]))


['No']
