In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv('gender_classification_v7.csv')
df

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0             1               11.8                 6.1          1          0   
1             0               14.0                 5.4          0          0   
2             0               11.8                 6.3          1          1   
3             0               14.4                 6.1          0          1   
4             1               13.5                 5.9          0          0   
...         ...                ...                 ...        ...        ...   
4996          1               13.6                 5.1          0          0   
4997          1               11.9                 5.4          0          0   
4998          1               12.9                 5.7          0          0   
4999          1               13.2                 6.2          0          0   
5000          1               15.4                 5.4          1          1   

      lips_thin  distance_nose_to_lip_long  gender  
0             1                          1    Male  
1             1                          0  Female  
2             1                          1    Male  
3             1                          1    Male  
4             0                          0  Female  
...         ...                        ...     ...  
4996          0                          0  Female  
4997          0                          0  Female  
4998          0                          0  Female  
4999          0                          0  Female  
5000          1                          1    Male  

[5001 rows x 8 columns]

In [3]:
df.shape

(5001, 8)

In [4]:
df.size

40008

In [5]:
df.head()

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0          1               11.8                 6.1          1          0   
1          0               14.0                 5.4          0          0   
2          0               11.8                 6.3          1          1   
3          0               14.4                 6.1          0          1   
4          1               13.5                 5.9          0          0   

   lips_thin  distance_nose_to_lip_long  gender  
0          1                          1    Male  
1          1                          0  Female  
2          1                          1    Male  
3          1                          1    Male  
4          0                          0  Female

In [6]:
df.tail()

long_hair  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
4996          1               13.6                 5.1          0          0   
4997          1               11.9                 5.4          0          0   
4998          1               12.9                 5.7          0          0   
4999          1               13.2                 6.2          0          0   
5000          1               15.4                 5.4          1          1   

      lips_thin  distance_nose_to_lip_long  gender  
4996          0                          0  Female  
4997          0                          0  Female  
4998          0                          0  Female  
4999          0                          0  Female  
5000          1                          1    Male

In [7]:
df.dtypes

long_hair                      int64
forehead_width_cm            float64
forehead_height_cm           float64
nose_wide                      int64
nose_long                      int64
lips_thin                      int64
distance_nose_to_lip_long      int64
gender                        object
dtype: object

In [8]:
#Checking the dataset is balanced or imbalanced data
df['gender'].value_counts()

gender
Female    2501
Male      2500
Name: count, dtype: int64

In [9]:
df.isna().sum()

long_hair                    0
forehead_width_cm            0
forehead_height_cm           0
nose_wide                    0
nose_long                    0
lips_thin                    0
distance_nose_to_lip_long    0
gender                       0
dtype: int64

In [10]:
x = df.iloc[:,:-1].values
x

array([[ 1. , 11.8,  6.1, ...,  0. ,  1. ,  1. ],
       [ 0. , 14. ,  5.4, ...,  0. ,  1. ,  0. ],
       [ 0. , 11.8,  6.3, ...,  1. ,  1. ,  1. ],
       ...,
       [ 1. , 12.9,  5.7, ...,  0. ,  0. ,  0. ],
       [ 1. , 13.2,  6.2, ...,  0. ,  0. ,  0. ],
       [ 1. , 15.4,  5.4, ...,  1. ,  1. ,  1. ]], shape=(5001, 7))

In [11]:
y = df.iloc[:,-1].values
y

array(['Male', 'Female', 'Male', ..., 'Female', 'Female', 'Male'],
      shape=(5001,), dtype=object)

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[ 1. , 15.1,  6.7, ...,  1. ,  1. ,  1. ],
       [ 1. , 12.6,  5.1, ...,  0. ,  0. ,  0. ],
       [ 1. , 11.9,  5.9, ...,  1. ,  1. ,  1. ],
       ...,
       [ 1. , 12. ,  5.9, ...,  0. ,  0. ,  0. ],
       [ 1. , 12.8,  5.4, ...,  0. ,  0. ,  0. ],
       [ 1. , 11.4,  5.5, ...,  0. ,  0. ,  0. ]], shape=(3500, 7))

In [13]:
x_test

array([[ 1. , 13.2,  5.7, ...,  1. ,  1. ,  1. ],
       [ 1. , 13.7,  6. , ...,  0. ,  0. ,  0. ],
       [ 0. , 12.9,  5.3, ...,  0. ,  0. ,  1. ],
       ...,
       [ 0. , 12.3,  6.6, ...,  1. ,  0. ,  1. ],
       [ 1. , 12.1,  5.7, ...,  1. ,  1. ,  1. ],
       [ 1. , 14.7,  6.7, ...,  1. ,  0. ,  0. ]], shape=(1501, 7))

In [15]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[ 0.38947996,  1.73652515,  1.39865907, ...,  0.99714693,
         1.01554945,  1.00630559],
       [ 0.38947996, -0.52376806, -1.5619135 , ..., -1.00286124,
        -0.98468863, -0.99373392],
       [ 0.38947996, -1.15665016, -0.08162721, ...,  0.99714693,
         1.01554945,  1.00630559],
       ...,
       [ 0.38947996, -1.06623843, -0.08162721, ..., -1.00286124,
        -0.98468863, -0.99373392],
       [ 0.38947996, -0.3429446 , -1.00680614, ..., -1.00286124,
        -0.98468863, -0.99373392],
       [ 0.38947996, -1.6087088 , -0.82177036, ..., -1.00286124,
        -0.98468863, -0.99373392]], shape=(3500, 7))

In [16]:
x_test

array([[ 1.00000000e+00,  1.32000000e+01,  5.70000000e+00, ...,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  1.37000000e+01,  6.00000000e+00, ...,
        -1.38936481e-16,  2.74256808e-16, -4.49862370e-16],
       [ 2.85930010e-16,  1.29000000e+01,  5.30000000e+00, ...,
        -1.38936481e-16,  2.74256808e-16,  1.00000000e+00],
       ...,
       [ 2.85930010e-16,  1.23000000e+01,  6.60000000e+00, ...,
         1.00000000e+00,  2.74256808e-16,  1.00000000e+00],
       [ 1.00000000e+00,  1.21000000e+01,  5.70000000e+00, ...,
         1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
       [ 1.00000000e+00,  1.47000000e+01,  6.70000000e+00, ...,
         1.00000000e+00,  2.74256808e-16, -4.49862370e-16]],
      shape=(1501, 7))

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)
from sklearn.naive_bayes import GaussianNB
base = GaussianNB()
from sklearn.svm import SVC
sv = SVC()

In [18]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [20]:
lst = [knn, base, sv]
for i in lst:
    print("Model name is ",i)
    i.fit(x_train,y_train)
    y_pred = i.predict(x_test)
    y_pred
    print("**********************************************************************************************")
    print("Model Confusion metrics is ")
    print(confusion_matrix(y_test,y_pred))
    print("**********************************************************************************************")
    print("Accuracy Score is")
    print(accuracy_score(y_test,y_pred))
    print("**********************************************************************************************")
    print("Classification Report is")
    print(classification_report(y_test,y_pred))

Model name is  KNeighborsClassifier(n_neighbors=7)
**********************************************************************************************
Model Confusion metrics is 
[[722  17]
 [ 35 727]]
**********************************************************************************************
Accuracy Score is
0.9653564290473018
**********************************************************************************************
Classification Report is
              precision    recall  f1-score   support

      Female       0.95      0.98      0.97       739
        Male       0.98      0.95      0.97       762

    accuracy                           0.97      1501
   macro avg       0.97      0.97      0.97      1501
weighted avg       0.97      0.97      0.97      1501

Model name is  GaussianNB()
**********************************************************************************************
Model Confusion metrics is 
[[715  24]
 [ 28 734]]
**************************************************